### PR TITLE
 Use Appsignal.Utils.warning/1 instead of Logger.warn/1

### PR DESCRIPTION
**Pull request by jeffkreeftmeijer**
Update the minimal version of the appsignal dependency to 2.7.4, which is the version that introduces the backwards compatible logging functions in `Appsignal.Utils`. Then, use `Appsignal.Utils.warning/1` in `Appsignal.Phoenix.View` and `Appsignal.Phoenix.EventHandler` to support Elixir 1.10 through 1.15.

Closes #69.

### CODE REVIEW

**Review by unflxw — APPROVED** [review]

**Comment by unflxw** [comment]
Wait, since this package depends on the AppSignal for Plug package, and this [also needs to be fixed in Plug](https://github.com/appsignal/appsignal-elixir-plug/blob/fe2a110407e946edbaf0327cde1d8b8ed74c8614/lib/appsignal_plug.ex#L40-L42), wouldn't it make sense to fix it there first, so we can bump the Plug version dependency here as well?

**Comment by jeffkreeftmeijer** [comment]
> Wait, since this package depends on the AppSignal for Plug package, and [this issue also needs to be fixed in that package](https://github.com/appsignal/appsignal-elixir-plug/blob/fe2a110407e946edbaf0327cde1d8b8ed74c8614/lib/appsignal_plug.ex#L40-L42), wouldn't it make sense to fix it there first, so we can bump the Plug version dependency here as well?

Ah, I did a quick search to see if the logger functions were used in that package. GitHub's search didn't find any (https://github.com/search?q=repo%3Aappsignal%2Fappsignal-elixir-plug%20Logger&type=code), so that's a cautionary tale. I'll patch appsignal-elixir-plug and will update this pull request. Keen eye as always, Noemi!

**Comment by jeffkreeftmeijer** [comment]
I've opened a [pull request on AppSignal for Plug](https://github.com/appsignal/appsignal-elixir-plug/pull/35), which is ready for review. That will probably be released as 2.0.14, but I'm not updating the mix.exs file in this repository as it would break the build, meaning this pull request is now awaiting an appsignal-plug release.

That said, since this branch has an updated dependency on AppSignal for Elixir, it can be tested without having a newer version of AppSignal for Plug.

**Review by tombruijn — APPROVED** [review]

**Review by luismiramirez — APPROVED** [review]

**Comment by jeffkreeftmeijer** [comment]
This patch was released as AppSignal for Phoenix 2.3.3. Thanks again for letting us know, @idyll!

**Comment by idyll** [comment]
Awesome. Thanks all!

**Pull request merged**
